name: sparcrl
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - absl-py=2.1.0
  - annotated-types=0.7.0
  - anyio=4.4.0
  - appnope=0.1.4
  - asttokens=2.4.1
  - astunparse=1.6.3
  - boto3=1.34.158
  - botocore=1.34.158
  - certifi=2024.7.4
  - charset-normalizer=3.3.2
  - cmlibs.argon=0.4.3
  - cmlibs.exporter=0.7.0
  - cmlibs.maths=0.6.2
  - cmlibs.utils=0.9.0
  - cmlibs.zinc=4.1.2
  - comm=0.2.2
  - contourpy=1.2.1
  - cycler=0.12.1
  - debugpy=1.8.1
  - decorator=5.1.1
  - distro=1.9.0
  - executing=2.0.1
  - flatbuffers=24.3.25
  - fonttools=4.53.1
  - gast=0.6.0
  - google-pasta=0.2.0
  - grpcio=1.65.4
  - grpcio-tools=1.62.3
  - h5py=3.11.0
  - h11=0.14.0
  - httpcore=1.0.5
  - httpx=0.27.0
  - idna=3.7
  - ipykernel=6.29.4
  - ipython=8.25.0
  - jedi=0.19.1
  - jiter=0.5.0
  - jmespath=1.0.1
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - keras=3.4.1
  - kiwisolver=1.4.5
  - libclang=18.1.1
  - markdown=3.6
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - matplotlib=3.9.1
  - matplotlib-inline=0.1.7
  - mbfxml2ex=0.7.3
  - mdurl=0.1.2
  - ml-dtypes=0.4.0
  - namex=0.0.8
  - nest-asyncio=1.6.0
  - numpy=1.26.4
  - openai=1.40.3
  - opt-einsum=3.3.0
  - optree=0.12.1
  - osparc=0.5.0
  - packaging=24.0
  - pandas=2.2.2
  - parso=0.8.4
  - pennsieve2=0.1.2
  - pexpect=4.9.0
  - pillow=10.4.0
  - pip=24.2
  - platformdirs=4.2.2
  - prompt_toolkit=3.0.46
  - protobuf=4.25.4
  - psutil=5.9.8
  - ptyprocess=0.7.0
  - pure-eval=0.2.2
  - pydantic=2.8.2
  - pydantic_core=2.20.1
  - pygments=2.18.0
  - pyjwt=2.9.0
  - pyparsing=3.1.2
  - python-dateutil=2.9.0
  - pytz=2024.1
  - pyzmq=26.0.3
  - requests=2.32.3
  - rich=13.7.1
  - s3transfer=0.10.2
  - scaffoldmaker=0.14.0
  - scipy=1.14.0
  - setuptools=72.1.0
  - six=1.16.0
  - sniffio=1.3.1
  - sparc.client=0.3.1
  - stack-data=0.6.3
  - style=1.1.0
  - svgpathtools-light=1.6.2
  - tensorboard=2.17.0
  - tensorboard-data-server=0.7.2
  - tensorflow=2.17.0
  - tensorflow-io-gcs-filesystem=0.37.1
  - termcolor=2.4.0
  - tornado=6.4.1
  - tqdm=4.66.5
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - tzdata=2024.1
  - update=0.0.1
  - urllib3=2.2.2
  - wcwidth=0.2.13
  - werkzeug=3.0.3
  - wheel=0.44.0
  - wrapt=1.16.0
  - pip:
      - openai==1.40.3
